<?php
# Generated by the protocol buffer compiler (spiral/php-grpc). DO NOT EDIT!
# source: import/service.proto

namespace Import;

use Spiral\GRPC;
use Import\Sub;

interface ServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "import.Service";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param Message $in
    * @return Message
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function SimpleMethod(GRPC\ContextInterface $ctx, Message $in): Message;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param Sub\Message $in
    * @return Sub\Message
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function ImportMethod(GRPC\ContextInterface $ctx, Sub\Message $in): Sub\Message;
}
