version: "2"
run:
  allow-parallel-runners: true
output:
  formats:
    text:
      path: stdout
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exhaustive
    - gochecknoglobals
    - goconst
    - gocritic
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - tparallel
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    dupl:
      threshold: 100
    goconst:
      min-len: 2
      min-occurrences: 3
    godot:
      scope: declarations
      capital: true
    lll:
      line-length: 120
    misspell:
      locale: US
    nolintlint:
      require-specific: true
    prealloc:
      simple: true
      range-loops: true
      for-loops: true
    wsl:
      allow-assign-and-anything: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - funlen
          - gocognit
          - scopelint
        path: _test\.go
    paths:
      - internal/debug/server_test.go
      - .github
      - .git
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - internal/debug/server_test.go
      - .github
      - .git
      - third_party$
      - builtin$
      - examples$
