// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package message

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Messages struct {
	_tab flatbuffers.Table
}

func GetRootAsMessages(buf []byte, offset flatbuffers.UOffsetT) *Messages {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Messages{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsMessages(buf []byte, offset flatbuffers.UOffsetT) *Messages {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Messages{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *Messages) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Messages) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Messages) Messages(obj *Message, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *Messages) MessagesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func MessagesStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func MessagesAddMessages(builder *flatbuffers.Builder, messages flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(messages), 0)
}
func MessagesStartMessagesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func MessagesEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
