name: Chore
description: 🧹 Enhancement or chore of the existing code
title: "[🧹 CHORE]: "
labels: ["C-enhancement"]
assignees:
  - rustatian
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this report!

  - type: checkboxes
    id: search-done
    attributes:
      label: No duplicates 🥲.
      options:
        - label: I have searched for a similar issue.
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What should be improved or cleaned up?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
