<?php
# Generated by the protocol buffer compiler (spiral/php-grpc). DO NOT EDIT!
# source: use_empty/service.proto

namespace Test;

use Spiral\GRPC;
use Google\Protobuf;

interface ServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "test.Service";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param Protobuf\GPBEmpty $in
    * @return Protobuf\GPBEmpty
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Test(GRPC\ContextInterface $ctx, Protobuf\GPBEmpty $in): Protobuf\GPBEmpty;
}
