{
 "title": "RoadRunner gRPC dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "RR uptime",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "rr_http_uptime_seconds", "legendFormat": "Uptime" }
   ]
  },
  {
   "title": "RR in-use memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "go_memstats_heap_inuse_bytes", "legendFormat": "RR memory" }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 0 },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "Green threads count" }
   ]
  },
  {
   "title": "gRPC workers state",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rr_grpc_total_workers", "legendFormat": "TOTAL" },
    { "expr": "rr_grpc_workers_ready", "legendFormat": "READY" },
    { "expr": "rr_grpc_workers_working", "legendFormat": "WORKING" },
    { "expr": "rr_grpc_workers_invalid", "legendFormat": "INVALID" }
   ]
  },
  {
   "title": "Workers total memory [gRPC]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "(rr_grpc_workers_memory_bytes/1024000)",
     "legendFormat": "Workers total memory used"
    }
   ]
  },
  {
   "title": "Memory by worker [gRPC]",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rr_grpc_worker_memory_bytes", "legendFormat": "PID: {{pid}}" }
   ]
  },
  {
   "title": "gRPC latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(rr_grpc_request_duration_seconds_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "gRPC requests queue size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "targets": [
    { "expr": "rr_grpc_requests_queue" }
   ]
  },
  {
   "title": "RPM [gRPC]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "rate(rr_grpc_request_total[1m])",
     "legendFormat": "RPM"
    }
   ]
  }
 ]
}