{
 "title": "RoadRunner temporal dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "RR uptime",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "rr_http_uptime_seconds", "legendFormat": "Uptime" }
   ]
  },
  {
   "title": "RR in-use memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "go_memstats_heap_inuse_bytes", "legendFormat": "RR memory" }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 0 },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "Green threads count" }
   ]
  },
  {
   "title": "RR-Temporal workers state",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rr_temporal_total_workers", "legendFormat": "TOTAL" },
    { "expr": "rr_temporal_workers_ready", "legendFormat": "READY" },
    { "expr": "rr_temporal_workers_working", "legendFormat": "WORKING" },
    { "expr": "rr_temporal_workers_invalid", "legendFormat": "INVALID" }
   ]
  },
  {
   "title": "Workers total memory [Temporal]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "(rr_temporal_workers_memory_bytes/1024000)",
     "legendFormat": "Workers total memory used"
    }
   ]
  },
  {
   "title": "Memory by worker [Temporal]",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rr_temporal_worker_memory_bytes",
     "legendFormat": "PID: {{pid}}"
    }
   ]
  }
 ]
}