#!/usr/bin/env php
<?php
/**
 * Automatic roadrunner builds.
 */

use Spiral\RoadRunner\QuickBuild\Builder;

require_once "src/Builder.php";

// load build config
$version = $argv[1] ?? "1.3.1";

// load build config
$config = $argv[2] ?? __DIR__ . "/.build.json";

// Greeting!
Builder::cprintf(
    "Building <green>RoadRunner</reset> specifically for you (version: <white>%s</reset>)...\n",
    $version
);

$builder = Builder::loadConfig($config);
if ($builder == null) {
    Builder::cprintf("<red>Unable to load config:</reset> %s\n", $config);
    return;
}

$errors = $builder->configErrors();
if (!empty($errors)) {
    Builder::cprintf("<yellow>Found configuration errors:</reset>\n");
    foreach ($errors as $error) {
        Builder::cprintf("- <red>%s</reset>\n", $error);
    }

    return;
}

// Start build
$builder->build(getcwd(), __DIR__ . '/main.go', 'rr', $version);