FROM archlinux:latest

ARG DEBIAN_FRONTEND=noninteractive
RUN pacman-key --init

RUN Y | pacman -Syu --noconfirm
RUN Y | pacman -S --noconfirm curl base-devel pkgconf

RUN curl -sL https://github.com/kr/beanstalkd/archive/v1.12.tar.gz | tar xvz -C /tmp

WORKDIR /tmp/beanstalkd-1.12
RUN make -j12
RUN cp beanstalkd /usr/bin

EXPOSE 11300
ENTRYPOINT ["/usr/bin/beanstalkd"]
